### ISSUE TITLE
Executable does not exists

### ISSUE THREAD

**Issue by EmanueleCoppola** [orchestral/testbench-dusk#21]
This "create-sqlite-db" executable is not available after composer update since there isn't in the release source code.
`
php vendor/orchestra/testbench-dusk/create-sqlite-db
`

Also the Options class is not included...

```php
// To show the UI during testing
\Orchestra\Testbench\Dusk\Options::withUI();

// To hide the UI during testing
\Orchestra\Testbench\Dusk\Options::withoutUI();
```

What...

**Comment by Keoghan** [comment]
I have just released a new version for 3.5 (3.5.5) with all those new bits in there, so those willow be available with a composer update.
