### ISSUE TITLE
Two different migrations, both called CreateUsersTable, may appear within a test suite 

### ISSUE THREAD

**Issue by bjuppa** [orchestral/testbench-dusk#26]
I really appreciate @crynobone's work in #6 that gives our Dusk tests the most likely Laravel skeleton for the task, as it matches the defaults of a fresh Laravel app, thanks a million!

However... with that comes a problem if you use [`loadLaravelMigrations()`](https://github.com/orchestral/testbench-core/blob/master/src/Concerns/WithLaravelMigrations.php).

### The problem
If your test suite includes some tests that extend the Dusk test class `\Orchestra\Testbench\Dusk\TestCase` and also some other tests that extend the "normal" test class `\Orchestra\Testbench\TestCase`, there could be **migrations loaded from both skeletons during the same test run**.

The Laravel migration classes are not namespaced so this is the error you may see when running your test suite:

`PHP Fatal error:  Cannot declare class CreateUsersTable, because the name is already in use in...`

### A solution
I solved this by making sure all integration tests in my test suite use the same Laravel skeleton (the one from `testbench-dusk`), regardless of the base class they extend. You can do that by overriding `getBasePath()` in your test class.

```php
/**
* Make sure all integration tests use the Laravel files of the testbench-dusk package.
*
* This avoids duplicate classes in migrations.
* Overrides \Orchestra\Testbench\Dusk\TestCase::getBasePath and
* \Orchestra\Testbench\Concerns\CreatesApplication::getBasePath
*
* @return string
*/
protected function getBasePath()
{
    return __DIR__.'/../vendor/orchestra/testbench-dusk/laravel';
}
```

I actually did that override in my `IntegrationTestSetupTrait` that I use in both dusk tests and other integration tests. But as long as the override is placed somewhere in your test class hierarchy so that it covers all integration test it should be fine! You may need to adjust the path depending on how many directories deep your test class lies in your own package structure (mine goes straight in the `/tests` directory).

Hope this can help someone that encounters the same problem!
I'm sorry I can't offer a suggestion as to how this could be solved in the testbench packages themselves though. Apart from namespacing the migrations in the skeletons, but that's probably not a good idea as it could have tons of other implications.

**Comment by crynobone** [comment]
That's seem a good solution, @bjuppa can you submit a PR to update the documentation regarding this.
