### ISSUE TITLE
White screen or unable to connect.

### ISSUE THREAD

**Issue by sarthaksavvy** [orchestral/testbench-dusk#28]
I have seen all the issues but can't find the solutions.

The problem is, I have configured this package properly but when I run dusk test like this

        $this->browse(function (Browser $browser) {
            $browser->visit('/admin')->dump();
        });

I am getting error in console like this 

`
"<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html>"
`

this comes when I use `\Orchestra\Testbench\Dusk\Options::withoutUI();`

but when I comment `\Orchestra\Testbench\Dusk\Options::withoutUI();` and run this test 

    $this->browse(function (Browser $browser) {
            $browser->visit('/admin/dashboard');
            $browser->assertSee('Hello');
        });

then I get screenshot of unable to connect
![failure-bitfumes_pulsar_tests_browser_dashboard_name-0](https://user-images.githubusercontent.com/41295276/44443576-0b9a4e80-a5f6-11e8-8bc3-2236687ecd31.png)

I have used this config

  
       protected static $baseServeHost = '127.0.0.1';
       protected static $baseServePort = 9000;

     protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('app.key', 'AckfSECXIvnK5r28GVIWUAxmbBSjTsmF');
        // $app['config']->set('database.default', 'testing');
        $app['config']->set('database.default', 'sqlite');
        $app['config']->set('database.connections.sqlite', [
            'driver'   => 'sqlite',
            'database' => ':memory:',
            'prefix'   => '',
        ]);
    }

    public static function setUpBeforeClass()
    {
        static::serve();
    }

    public static function tearDownAfterClass()
    {
        static::stopServing();
    }

Please help

**Comment by s-sarthak** [comment]
Please refer to this repo and see what I have used and what I have done wrong.
https://github.com/s-sarthak/pulsar-the-admin

**Comment by Keoghan** [comment]
Hi - I have popped you over a PR which I hope helps.

I think we need to make a change to TestBench Dusk after working through it, so we can avoid affecting the database when creating the DuskServer - I've noted that in the PR. https://github.com/s-sarthak/pulsar-the-admin/pull/1

**Comment by crynobone** [comment]
Fixed in sarthaksavvy/pulsar-the-admin#1
