### ISSUE TITLE
How to register routs?

### ISSUE THREAD

**Issue by tabuna** [orchestral/testbench-dusk#3]
Hi, how can I specify the registration of the package?

Dusk does not see the routing specified in the package. What am I doing wrong?

What did you do:

```php
namespace Orchid\Platform\Tests;

use Orchestra\Testbench\Dusk\TestCase;

abstract class TestBrowserCase extends TestCase
{
  /**
     * Setup the test environment.
     */
    public function setUp()
    {
        parent::setUp();

        Schema::defaultStringLength(191);

        $this->loadLaravelMigrations('orchid');

        $this->artisan('migrate', [
           '--database' => 'orchid',
       ]);

        $this->withFactories(__DIR__.'/../database/factories');
    }

    /**
     * @param \Illuminate\Foundation\Application $app
     */
    protected function getEnvironmentSetUp($app)
    {
        // set up database configuration
        $app['config']->set('database.connections.orchid', [
            'driver'   => 'pgsql',
            'host'     => '127.0.0.1',
            'port'     => '5432',
            'database' => 'platform',
            'username' => 'orchid',
            'password' => 'orchid',
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
            'sslmode'  => 'prefer',
        ]);
        $app['config']->set('database.default', 'orchid');
    }

    /**
     * @param \Illuminate\Foundation\Application $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            FoundationServiceProvider::class,
        ];
    }

    /**
     * @param \Illuminate\Foundation\Application $app
     *
     * @return array
     */
    protected function getPackageAliases($app)
    {
        return [
            'Dashboard' => Dashboard::class,
            'Alert'     => Alert::class,
            'Active'    => Active::class,
        ];
    }

    public static function setUpBeforeClass()
    {
        static::serve();
    }

    public static function tearDownAfterClass()
    {
        static::stopServing();
    }
}

```

**Comment by Keoghan** [comment]
Hi @tabuna, 

What error do you receive? It looks like you may need to add the full namespace for the FoundationServiceProvider?

Thanks, Keoghan

**Comment by tabuna** [comment]
I have combined several files to write it down here. I do [differently](https://github.com/orchidsoftware/platform/tree/master/tests), but it does not change the essence.
There are no syntax errors. But my routs are inaccessible to me. And the server does not shut down by the way, it has to be disconnected through the console after each launch.

**Comment by Keoghan** [comment]
Ok, thanks. I’ll do my best to take a look this evening to see what I can find.

**Comment by tabuna** [comment]
[Video.mp4.zip](https://github.com/orchestral/testbench-dusk/files/1628548/2018-01-13.20.31.40.mp4.zip)

**Comment by Keoghan** [comment]
OK, I've installed your project locally and played around a little. (I needed to exclude the migrations/db setup to test).

I think the primary issue is that you are trying to get to a route by it's name - so you need to use `$browser->visitRoute('dashboard.login')`. (My local copy works with that change and the below).

Once that is working, there is then a laravel mix issue. I have solved that in another project by adding a dummy elixir manifest during setUp. (I discovered this locally looking in the log at `vendor/orchestra/testbench-core/laravel/storage/logs/`. 

```php

protected function addDummyMixManifest()
    {
        $manifestDir = __DIR__ . '/../vendor/orchestra/testbench-core/laravel/public/orchid';
        @mkdir($manifestDir);

        file_put_contents(
            $manifestDir . '/mix-manifest.json',
            json_encode([
                'css/all.css' => '',
                'js/all.js' => '',
            ])
        );
    }
```


I've not tracked down why exactly the server doesn't always shutdown. It might be possible to register a shutdown hook somewhere to kill that additional process, maybe :)

**Comment by tabuna** [comment]
Fantastic. It works. Thank you very much. You made me happy
