### ISSUE TITLE
Laravel 5.8 Compatibility

### ISSUE THREAD

**Issue by mikebronner** [orchestral/testbench-dusk#33]
Hi guys! Posting this to track the progress for Laravel 5.8 compatibility. Thanks for all your work on this!

**Comment by DarkGhostHunter** [comment]
Same. Cannot test on Laravel 5.8.

**Comment by Keoghan** [comment]
I've made a start on this in the master branch - tests have passed locally but Travis is proving a challenge :)

**Comment by crynobone** [comment]
https://github.com/orchestral/testbench-dusk/releases/tag/v3.8.0
