### ISSUE TITLE
ServiceProviders does not work same as in regular Laravel app

### ISSUE THREAD

**Issue by MarekGogol** [orchestral/testbench-dusk#38]
Hello,

I am wondering if ServiceProviders boots in correct order of laravel initialization.

If you create **AppServiceProvider** and register this provider into 

**config/app.php** (same behaviour with `getPackageProviders($app)` method)
```
'providers' => [
    ...
    Illuminate\View\ViewServiceProvider::class,

    ...
    App\YourAppServiceProvider::class,
```

**YourAppServiceProvider.php**
```
class YourAppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        dd(request()->segments());
    }
}

```

Your provider in testbench-core app will not work same as in regular laravel.

If you open **localhost.test/a/b** route in original Laravel environment, you will see array with 2 keys
`array:2 [▼
  0 => "a"
  1 => "b"
]`

If you open same route, in testing environment, you will see empty array, what is problem, because app does not acts same as in regular laravel environment. In this case, I can't test package properly.

Used versions:
```
"orchestra/testbench": "^3.8",
"orchestra/testbench-dusk": "^3.8"
```

Other info:
- when I tested this bug in pure laravel dusk, it works properly
- orchestra/testbench has same problem
- I think problem is in boot order of all laravel service providers, they boot before symfony core?

Thank you for quick response.

**Comment by crynobone** [comment]
In Laravel, the sequence of which Service Provider get to loads first shouldn't matter, and this has been mentioned by Taylor Ot'well in various occasion. 

So when I setup Testbench in general developers should be aware that this might happen, and prepared for it.

**Comment by crynobone** [comment]
Also, Testbench bootstrap Laravel under command line environment first before a HTTP request occur (All service providers booted earlier than HTTP request). Therefore the `Request` object isn't available until a test make a request.

**Comment by MarekGogol** [comment]
First of all, thank you for really fast response.

Maybe i wrote this issue in not right way, sorry for that. Problem is not with boot order of service providers, but with requests data itself, I describe below... Of course, It does not matter if providerA boots before providerB, its okay and thats right. 

But I meant, something must be wrong in testbench providers at all, because when you want receive REQUEST_URI, it is not available also when it should be. I spend couple of hours of debugging your package, and I figure out, that all service providers boots before symfony requests kernel, which may cause problem.

Here is example of bug in testbench environment when you dump `dd(url()->current(), request()->segments(), request()->server);` in your service provider... 
![image](https://user-images.githubusercontent.com/11134410/57389507-a0f86580-71ba-11e9-8a06-09026ce9e2ef.png)


In laravel app, this property is set correctly:
![image](https://user-images.githubusercontent.com/11134410/57389495-9938c100-71ba-11e9-9294-ac31ed59a766.png)

**Comment by MarekGogol** [comment]
> Also, Testbench bootstrap Laravel under command line environment first before a HTTP request occur (All service providers booted earlier than HTTP request). Therefore the `Request` object isn't available until a test make a request.

Yes, this I tried to say. Please, how should I solve this situation when I need receive url data in my provider? For example I need set language...
![image](https://user-images.githubusercontent.com/11134410/57390049-c3d74980-71bb-11e9-84a6-09f04f624c0f.png)

**Comment by crynobone** [comment]
Shouldn't you be using Laravel event to listen to [Illuminate\Routing\Events\RouteMatched](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Routing/Events/RouteMatched.php) to handle this scenario?

**Comment by MarekGogol** [comment]
Thank you for this event, I tried it out, but when page occurs error 404, or route is simply not matched, then language wont be set. This is just one of many examples/cases where I need to track url segments. 

- On many places in project I use statement `Admin::isAdmin() === true` which compares first segment is "admin". So return value need to be synchronous. If I would use events, it would causes lot of problems...

- I also tried `Illuminate\Foundation\Http\Events\RequestHandled` event, but it is too late for language change. Blades are rendered with default language already, and also it won't solve last problem in next point.

- Other more complex scenario is, I register routes dynamically according to selected language from database. I need check if app can retrieve data from DB, because I do not need register routes in admin interface. This everything need to be done before router is initialized/matched. Why do I need register routes dynamically? I need change prefix of all *(for example)* **web.php** routes at /en/ or /de/ prefix. So then /contact will be available also on /en/contact page.

Thanks.

**Comment by crynobone** [comment]
The same tests would also failed in a basic Laravel application without any modification. So I not planning to change anything with Testbench Core. 

As for Testbench Dusk, I'll leave this up to @Keoghan if he's interested.

**Comment by MarekGogol** [comment]
> The same tests would also failed in a basic Laravel application without any modification. So I not planning to change anything with Testbench Core.
> 
> As for Testbench Dusk, I'll leave this up to @Keoghan if he's interested.

Really? I tested avaiability of segment and url in laravel enviroment and everything was available as excepts. In testbench this variables are not available :(.

I created basic test repo with dusk setup and one test example:
https://github.com/MarekGogol/laravel-test-request-available
```
git clone https://github.com/MarekGogol/laravel-test-request-available.git test-bug
cd test-bug
composer install
php artisan dusk:install
php artisan dusk
```

Thank you

**Comment by crynobone** [comment]
I'm talking about Testbench vs TestCase default by Laravel here. Not Testbench Dusk vs Laravel Dusk

**Comment by crynobone** [comment]
![Screen Shot 2019-05-09 at 7 10 57 AM](https://user-images.githubusercontent.com/172966/57414174-9e812480-7229-11e9-8901-6005276d7cba.png)

Carefully read what I wrote above!

**Comment by MarekGogol** [comment]
You right, now I understand. Thank you for explanation. So it's **testbench-dusk** vs **laravel dusk**. I will have to figure other ways in basic laravel TestCase, maybe after little research I would write issue into Laravel, I'll see... Thank you for your time @crynobone , wish you the best. Hope It would be fixed in testbench-dusk somehow.

**Comment by MarekGogol** [comment]
Fixed by, hope won't break anything else.

```   
protected function getEnvironmentSetUp($app)
{
     $app->handle(\Illuminate\Http\Request::capture());
}   
```
