### ISSUE TITLE
How to run correctly in CI?

### ISSUE THREAD

**Issue by tabuna** [orchestral/testbench-dusk#40]
Please tell me how to properly assemble with CI help.
For example, for travic-ci:

```php
language: php
dist: bionic

php:
  - 7.3

before_script:
   - vendor/bin/dusk-updater detect --auto-update
   - vendor/orchestra/testbench-dusk/create-sqlite-db
  -  google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - vendor/bin/phpunit --testsuite=Browser
```

Why am I doing this instead of checking? I tried a few options and they give slightly different results, which greatly confuses me, for example:

- Do I need to add 'addons: chrome: stable' as specified in the laravel [documentation](https://laravel.com/docs/6.x/dusk#running-tests-on-travis-ci)?

- If you run 'vendor/bin/dusk-updater update ', the result is:
`
ChromeDriver binary successfully installed for version 78.0.3904.105.
`

- If you check with 'vendor/bin/dusk-updater detect --auto-update ', I get a warning
```
 ----------------- ----------- 
  Installed         Version    
 ----------------- ----------- 
  Chrome/Chromium   76.0.3809  
  ChromeDriver      78.0.3904  
 ----------------- ----------- 
 ! [CAUTION] ChromeDriver is outdated!                                          
ChromeDriver binary successfully installed for version 76.0.3809.126.
```

At the same time, I get strange test results, which are very different from the test on the local machine. Any help will be useful.

**Comment by crynobone** [comment]
`vendor/bin/dusk-updater update` will always download the binaries regardless if you already cached the latest ChromeDriver in your CI.

**Comment by Keoghan** [comment]
Hi @tabuna, 

Are you able to share the repo that you are having trouble with?

There are a few repo's using testbench dusk with Travis - one here: https://github.com/kontenta/kontour/blob/master/.travis.yml

It's a bit tricky to advise on the strange test results without seeing them.

**Comment by tabuna** [comment]
Hi @Keoghan 

Ready to provide everything you need, you helped me a year ago, now I decided to do it again.
Added for this project: https://github.com/orchidsoftware/platform/tree/dusk
The `.travis` file has [additional instructions](https://github.com/orchidsoftware/platform/blob/dusk/.travis.yml#L1-L64)

Executable log::
https://travis-ci.org/orchidsoftware/platform/jobs/622844991


I get two errors:
  -  [testLogout](https://github.com/orchidsoftware/platform/blob/6ee7069c5f88c1577699ed4c681135cbf41e3aa3/tests/Browser/LoginTest.php#L44-L76)
- [testEditPage](https://github.com/orchidsoftware/platform/blob/dusk/tests/Browser/UserEditTest.php#L12-L32)

Both errors are very strange for me, the first I can get on the local machine if it is executed last. If this is indicated explicitly: `vendor/bin/phpunit --testsuite=Browser --filter=testLogout`. Thats all right

The second one did not repeat on the local machine, I get it only in  `Travis/GitHub Action`

**Comment by Keoghan** [comment]
Thanks @tabuna - I'll try to get some time today to take a look :)

**Comment by Keoghan** [comment]
Hi @tabuna, 

I don't think these errors are cause by your CI setup with Testbench Dusk. I'm not entirely sure what is causing the first error, but replacing the login sequence with the 'loginAs' appears to resolve the issue with the test breaking, and I think still tests the logout functionality appropriately.

The second feels like the browser hasn't quite loaded as the assertion is run, or there is some sort of delay occuring on the CI system. Perhaps you could try waiting for the specific text to appear before the final assertion?

**Comment by tabuna** [comment]
Hi @Keoghan 

> I don't think these errors are cause by your CI setup with Testbench Dusk. I'm not entirely sure what is causing the first error, but replacing the login sequence with the 'loginAs' appears to resolve the issue with the test breaking, and I think still tests the logout functionality appropriately.

You are right that this is probably not the problem of this package, I indicated it for the question of a more experienced specialist in this. No problem, we just transfer it to another place.

> The second feels like the browser hasn't quite loaded as the assertion is run, or there is some sort of delay occuring on the CI system. Perhaps you could try waiting for the specific text to appear before the final assertion?

Tried to indicate pause before confirming value

```php
//...
->press('Apply')
->waitForText('User was saved.')
->pause(100000)
->assertSee($user->name.'-async-test');
//..
```
This did not help me. Thank you for your time.
