### ISSUE TITLE
Dusk v6 release

### ISSUE THREAD

**Issue by barryvdh** [orchestral/testbench-dusk#48]
Is is possible to prepare a Dusk 6 release branch, for Laravel 8? So we can start testing Laravel 8 packages before the release?
Thanks!

**Comment by crynobone** [comment]
Sure, but `dev-master` or `"orchestra/testbench-dusk": "^6.0"` right now should allow tests against Laravel 8.

**Comment by barryvdh** [comment]
Hmm, I tried that in https://github.com/barryvdh/laravel-debugbar/pull/1097 but it fails (eg. in https://github.com/barryvdh/laravel-debugbar/pull/1097/checks?check_run_id=1040482927 )

Not really sure what is conflicting then

**Comment by crynobone** [comment]
Just make on push to use `laravel/nova` `^6.5` instead of `dev-master`. Should work now.

**Comment by barryvdh** [comment]
Thanks, it works now :)

**Comment by crynobone** [comment]
Welcome, thanks for letting me know about this. 

Proper branch should be available soon.
