### ISSUE TITLE
After Upgrading Package Unable To Run PHPUnit

### ISSUE THREAD

**Issue by mikebronner** [orchestral/testbench-dusk#49]
- Testbench Version: 6.0.0
- Laravel Version: 8.0.0
- PHP Version: 7.4
- Database Driver & Version: n/a

### Description:
```
1) GeneaLabs\LaravelSignInWithApple\Tests\Browser\SignInWithAppleTest::testButtonIsRendered
Facebook\WebDriver\Exception\UnknownServerException: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}),platform=Linux 5.4.0-47-generic x86_64)

/home/forge/laravel-sign-in-with-apple/vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:175
/home/forge/laravel-sign-in-with-apple/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:376
/home/forge/laravel-sign-in-with-apple/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:136
/home/forge/laravel-sign-in-with-apple/vendor/orchestra/testbench-dusk/src/TestCase.php:106
/home/forge/laravel-sign-in-with-apple/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:200
/home/forge/laravel-sign-in-with-apple/vendor/laravel/framework/src/Illuminate/Support/helpers.php:234
/home/forge/laravel-sign-in-with-apple/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:201
/home/forge/laravel-sign-in-with-apple/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:95
/home/forge/laravel-sign-in-with-apple/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:65
/home/forge/laravel-sign-in-with-apple/tests/Browser/SignInWithAppleTest.php:16
```

### Repo with issue
https://github.com/GeneaLabs/laravel-sign-in-with-apple

I have no idea if the issue is down to test bench-dusk, my package, or something in-between (maybe something in the upgrade process?). Any suggestions welcome :) thanks!

I have `google-chrome` installed:
```
❯ /usr/bin/google-chrome --version
Google Chrome 85.0.4183.102 
```

**Comment by crynobone** [comment]
https://github.com/orchestral/testbench-dusk/compare/5.x...6.x

There no significant changes on our end and I don't believe Laravel Dusk introduce anything significant as well. 

Have you tried force kill any chrome process on the machine?

**Comment by mikebronner** [comment]
@crynobone Thanks for the follow-up. I don't show any chrome processes running, and have also rebooted, just to make sure. I googled the heck out of this error, but couldn't find any solutions that seemed to fit the bill. The google-chrome version matches the driver as well:

```
❯ ./vendor/bin/dusk-updater detect --auto-update
 ----------------- ----------- 
  Installed         Version    
 ----------------- ----------- 
  Chrome/Chromium   85.0.4183  
  ChromeDriver      85.0.4183  
 ----------------- ----------- 
```

**Comment by Keoghan** [comment]
@mikebronner are you still having this issue?

**Comment by mikebronner** [comment]
@Keoghan Unfortuantely, yes. :) Do you have any ideas?

**Comment by Keoghan** [comment]
Looking around there are a couple of possibilities, which involve adding some extra options:

explicitly setting the debugging port with `--remote-debugging-port=0`  (0 will stop it trying to connect to one)

`--no-sandbox` and `--disable-dev-shm-usage`

the primary search for me was the `DevToolsActivePort file doesn't exist` part which I think is the primary cause of your issue there.

Have you tried any of those by any chance by customising the driver() method?

**Comment by crynobone** [comment]
Just an update, I still unable to replicate the issue.

**Comment by tu6ge** [comment]
I had the same problem，and after restart computer, this problem is vanish. when you first install this package , you can recurrence this bug

**Comment by tu6ge** [comment]
I install this package in win10, and in ubuntu 20.04,The bug can replicate

**Comment by Keoghan** [comment]
Very sorry folks, I am also unable to replicate (testing with the package that @mikebronner shared). I have tried fresh installing on my mac and a VM with ubuntu 20.04

**Comment by tu6ge** [comment]
Can replicate it in github actions

**Comment by Keoghan** [comment]
Happy to review if you're able point me to where I can 👍

**Comment by tu6ge** [comment]
I and my rranslation software is  don't  understand what you mean.

**Comment by Keoghan** [comment]
> I and my translation software is don't understand what you mean.

Sorry, do you have a github action set up that I can review?

**Comment by Keoghan** [comment]
I have created a simple test repo using testbench dusk and Github Actions.

https://github.com/Keoghan/testbench-dusk-test

Happy for you to PR something that shows the issue if you can replicate, @mikebronner @tu6ge

**Comment by tu6ge** [comment]
I have two commit [solve the problem](https://github.com/tu6ge/laravel-form-item/actions/runs/377320422), [Unsolved Problems](https://github.com/tu6ge/laravel-form-item/runs/1438231908?check_suite_focus=true). You can see their diff code

**Comment by tu6ge** [comment]
[This](https://github.com/tu6ge/laravel-form-item/commit/5cbdb631b20f7cdcd6b00ad358322da96a5430af) is the commit info

**Comment by tu6ge** [comment]
I am not found `vendor/laravel/dusk/bin/chromedriver-linux` in your document. and in laravel dusk document is not found it.

**Comment by Keoghan** [comment]
Ok - so it looks like your issues are now resolved @tu6ge?

**Comment by tu6ge** [comment]
Yes

**Comment by Keoghan** [comment]
@mikebronner are you still experiencingthese issues?

**Comment by mikebronner** [comment]
Hi @Keoghan, sorry for being absent here. I have not had a chance to retest yet, been super busy on other projects and gave up on the original project I was using this in. I tried following the thread, but am not understanding what the solution ended up being.

**Comment by Keoghan** [comment]
No worries @mikebronner. 

In tu6ge's case he needed to get chromedriver-linux running in the test container on Github Actions before running the tests. Not sure if yours will be the same.

**Comment by mikebronner** [comment]
Ah, no. I had that installed and running. Go ahead and close. I will report back if I do run into this in the future.
