### ISSUE TITLE
Laravel 404 page on every route

### ISSUE THREAD

**Issue by robov** [orchestral/testbench-dusk#54]
When I visit any route I get a screenshot of the standard laravel 404 page.
If I visit a page on the open internet I get a nice screenshot of that page, so the browser etc is working. However I cannot seem to get any of my own routes that I have registered

**Comment by crynobone** [comment]
I don't how I can helps debug above issue, and I'm using Testbench Dusk on daily basis for work related task.

**Comment by robov** [comment]
thanks anyway...this is a package that I am developing, so the entire laravel app is supplied by orchestra. the normal phpunit tests work like a charm even getting the same route... but visiting through dusk I get a 404

**Comment by robov** [comment]
and when I dump the routes before I visit them I see that the routes are registered

**Comment by robov** [comment]
hmmm...
When I visit one of the 3 default routes : $browser->visit('/_dusk/user')
Then I do get a valid return
Buy any other routes that are visible in Route::getRoutes() get a 404
even  $browser->visit('/')

**Comment by robov** [comment]
I found the problem, only not yet the sollution

In my PackageServiceProvider:Boot 
I register macros for the routes

in my phpunit feature tests 
I call these markros in the setup class... this works all fine and routes are correctly registered

in my dusk I do the same
But these routes are not registered. When I add the route manually to the PackageServiceProvider:Boot  (without use of macros) then the route can be visited in DUSK

It seems that calling the makros in the setup after parent::setup is too late and the routes are not regsitered
However calling them bore the parent::setup, then I get an error about missing facades

Kinda lost where to call my macros for dusk now

**Comment by robov** [comment]
As a fix I now register my routes (by calling the macros) now in the boot method of the serviceprovider in case of environment = testing.
I rather have this logic in the testcase, but at least this workaround works

**Comment by crynobone** [comment]
I don't think I follow what you're saying now, can you provide a reproducing code so we can take a look at it.
