### ISSUE TITLE
loginas works but not on backend

### ISSUE THREAD

**Issue by robov** [orchestral/testbench-dusk#55]
When I try to call my backend
            $browser->loginAs(User::find(1))
                ->assertAuthenticated()

This assertion is ok, so I expect the user to be logged in
When I then visit my page

            $browser->loginAs(User::find(1))
                ->assertAuthenticated()
                ->visit('/projects')

Then I get an error on my controller as Auth::user() returns NULL

I am developing a package and I use orchestra testbench and orchestra testbench dusk with no custom middelware or authentication guards

**Comment by crynobone** [comment]
Can you provide a reproducing code so we can take a look at it.

**Comment by robov** [comment]
Solved
The problem was that my routes did not include my auth middelware... hence the backend did not see it as an authenticated user
Adding the auth middelwares to the routes solved the issue
