### ISSUE TITLE
Testbench Dusk should maintain own Laravel skeleton

### ISSUE THREAD

**Issue by crynobone** [orchestral/testbench-dusk#6]
Current testbench uses Laravel skeleton optimized for unit and feature test, Testbench Dusk should instead mimick `laravel/laravel` skeleton as much as possible.

See orchestral/testbench-core#8 for related issues on this.

**Comment by Keoghan** [comment]
@crynobone which version would you like to target with this?

**Comment by crynobone** [comment]
Done on all maintained branch.

**Comment by Keoghan** [comment]
Sweet, thanks @crynobone
