### ISSUE TITLE
applicationBasePath method error

### ISSUE THREAD

**Issue by enkhtulga-gantsagaan** [orchestral/testbench-dusk#77]
- Testbench Version: 7.20.0
- Laravel Version: 9.19
- PHP Version: 8.1.8
- Database Driver & Version:

### Description:

When I try to use `applicationBasePath` method for skeleton then error occurred ` Class "App\Providers\RouteServiceProvider" not found`.

![image](https://user-images.githubusercontent.com/100667943/216250315-0cd4c911-bd95-4bd9-9f4d-cc59228a5adb.png)

### Steps To Reproduce:
Added `applicationBasePath()` method in `DuskTestCase.php`:

```
#DuskTestCase.php

abstract class DuskTestCase extends BaseTestCase
{

    /**
     * The base serve host URL to use while testing the application.
     *
     * @var string
     */
    protected static $baseServeHost = 'localhost';
    
    /**
     * Get Application base path.
     *
     * @return string
     */
    public static function applicationBasePath()
    {
        return __DIR__.'/../../../../laravel';
    }
   ...
}
```

**Comment by crynobone** [comment]
If you are defining a custom skeleton you need to ensure all required class is available based on how the skeleton is setup.

**Comment by enkhtulga-gantsagaan** [comment]
How to setup? I cannot find any topic in documentation. Thanks
