### ISSUE TITLE
Dusk environment seems not to work

### ISSUE THREAD

**Issue by eklundkristoffer** [orchestral/testbench-dusk#8]
For some reason dusk does not load the custom `.env.dusk.{environment}` file, but it does load the `.env` file just fine.

Any ideas?

Thanks.

**Comment by crynobone** [comment]
We recommend using `phpunit.xml` to store environment variable. See <https://github.com/orchestral/testbench/issues/211> for more details.

**Comment by eklundkristoffer** [comment]
I have tried that, seems to work fine with `APP_URL` but for some reason i cannot set the `DB_CONNECTION`, it always fall back to the one set inside the `.env` file.

phpunit.xml.dist:
```xml
<php>
    <env name="DB_DATABASE" value="hellhound_test"/>
</php>
```

**Comment by crynobone** [comment]
Why do you have `.env` file inside a Laravel package project?

**Comment by eklundkristoffer** [comment]
Not inside the package, it get the `.env` file from the root directory of the Laravel project.

**Comment by crynobone** [comment]
We don't load that file. I fail to see how this is Testbench Dusk issue.

**Comment by Keoghan** [comment]
@eklundkristoffer testbench and testbench dusk are not intended to be used inside a Laravel application.

They’re intended to give your package access to the Laravel framework for testing, by mimicking the package being included in an app - and giving you good control of it for your tests.

I can share an example if that helps you?

**Comment by eklundkristoffer** [comment]
Thanks for the help @Keoghan, a demo would be great. But first I gonna try to explain more deeper what I try to do.

So, I currently have:
~/Sites/projects/testing (fresh laravel 5.6 application http://testing.test)
~/Sites/packages/testing (loaded into the testing laravel application using composer)

So if i go to http://testing.test, everything looks good. So now I want to run the tests, i cd into `~/Sites/packages/testing` and run `composer install` and then`phpunit`. But it is most likely wrong since it also seems to load my `~/Sites/projects/testing/.env` file and i cannot overwrite the `DB_DATABASE` env.

Any idea what am doing wrong? again, thanks for the help guys.

my `~/Sites/packages/testing/phpunit.xml` file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
     backupStaticAttributes="false"
     bootstrap="vendor/autoload.php"
     colors="true"
     convertErrorsToExceptions="true"
     convertNoticesToExceptions="true"
     convertWarningsToExceptions="true"
     processIsolation="false"
     stopOnFailure="false"
     syntaxCheck="false">
    <testsuites>
        <testsuite name="Browser">
            <directory suffix="Test.php">./tests/Browser</directory>
        </testsuite>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
    </testsuites>
    <php>
        <env name="APP_KEY" value="base64:Xgs1LQt1GdVHhD6qyYCXnyq61DE3UKqJ5k2SJc+Nw2g="/>
        <env name="APP_ENV" value="testing"/>
        <env name="APP_URL" value="http://testing.test"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
    </php>
    <filter>
        <whitelist addUncoveredFilesFromWhitelist="false">
            <directory suffix=".php">src/</directory>
        </whitelist>
    </filter>
</phpunit>
```

**Comment by crynobone** [comment]
`<env name="APP_URL" value="http://testing.test"/>`

When you do this, the `testbench-dusk` will load external URL instead of `http://localhost`. Obviously this is an external application where `~/Sites/packages/testing/` has no control of. Again as I mention we don't load `.env`.

**Comment by Keoghan** [comment]
Crynobone is spot on, you need to use http://127.0.0.1:8000 as your APP_URL in PHPUnit.xml

This is because testbench-dusk boots up its own little php server to run the tests. Otherwise, you’re just browsing your full app at testing.test.

**Comment by eklundkristoffer** [comment]
@Keoghan , ah I see. I was actually trying that, but I only got some error. I found out the process listening on port 8000, killed it and after that it was working. The only problem I have now is that my AJAX requests is giving me 419 unknown status. Will look into it.

Thanks for the help!

**Comment by Keoghan** [comment]
No problem. I have been working on some improvements to warn if the server cannot be set up properly, and to cleanly shutdown in cases where the php process ends earlier than expected. Hope to get those in soon.
