### ISSUE TITLE
Unable to login as a user

### ISSUE THREAD

**Issue by dasundev** [orchestral/testbench-dusk#97]
- Testbench Version: 8.24
- Laravel Version: 10.0
- PHP Version: 8.3
- Database Driver & Version: SQLite

### Description:
I tried to run a test as a user but it failed and captured this screenshot.

![checkout](https://github.com/orchestral/testbench-dusk/assets/54996800/3aae9699-ce86-4270-ac70-f59ab782f4d3)

### Steps To Reproduce:
```php
public function it_can_render_checkout_page()
{
    $user = User::factory()->create();

    $this->browse(function (Browser $browser) use ($user) {
        $browser->loginAs($user)
            ->visit('checkout')
            ->screenshot('checkout');
    });
}
```

**Comment by crynobone** [comment]
It's impossible to get this error on Laravel 10. 

https://laravel.com/docs/11.x/authentication#redirecting-unauthenticated-users

You can customise this via `workbench/bootstrap/app.php` but that's only going to be used for Laravel 11 and Testbench Dusk 9
